{'plugins', 'repo', 'Shougo', 'neomru', 'vim', 'on_path', 'jiangmiao', 'auto', 'pairs', 'on_i', 'neoyank', 'neosnippet', 'depends', 'snippets', 'on_ft', 'snippet', 'neocomplete', 'has', 'lua', 'deoplete', 'nvim', 'unite'}
