[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif dein#util#_is_mac()
    let cmd = 'make -f make_mac.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''
""build = 'make'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
  let g:rehash264 = 1
  au VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
  set termguicolors
  set background=dark
  let g:edge_style = 'neon'
  let g:edge_disable_italic_comment = 1
  au VimEnter * nested colorscheme edge
'''

[[plugins]]
repo = 'gruvbox-material/vim'
hook_add = '''
  set termguicolors
  set background=dark
  let g:gruvbox_material_background = 'soft'
  au VimEnter * nested colorscheme gruvbox-material
'''

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'hashivim/vim-terraform'
hook_add = '''
  let g:terraform_fmt_on_save = 1
  let g:terraform_align = 1
  let g:terraform_fold_section = 1
'''

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merge = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
