tap "fujiwara/tap"
tap "idoavrah/homebrew"
tap "k1low/tap"
tap "kayac/tap"
tap "kreuzwerker/taps"
tap "pulumi/tap"
tap "supabase/tap"

# Core tools
brew "bat"
brew "direnv"
brew "eza"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "gitui"
brew "glow"
brew "grep"
brew "jq"
brew "jnv"
brew "lazygit"
brew "ripgrep"
brew "sheldon"
brew "tig"
brew "tree"
brew "wget"
brew "zoxide"

# Development
brew "go-task"
brew "graphviz"
brew "jsonnet"
brew "luajit", args: ["HEAD"]
brew "luarocks"
brew "openjdk"
brew "plantuml"
brew "pngpaste"
brew "pnpm"
brew "uv"
brew "yarn"

# Container / Kubernetes
brew "act"
brew "helm"
brew "helmfile"
brew "kind"
brew "kubernetes-cli"
brew "kubectx"
brew "kustomize"
brew "minikube"
brew "skaffold"

# Cloud / Infrastructure
brew "argocd"
brew "azure-cli"
brew "circleci"
brew "eksctl"
brew "terraformer"
brew "terragrunt"
brew "tfsec"
brew "fujiwara/tap/ecrm"
brew "idoavrah/homebrew/tftui"
brew "k1low/tap/tbls"
brew "kayac/tap/ecspresso"
brew "kreuzwerker/taps/m1-terraform-provider-helper"
brew "pulumi/tap/pulumi"
brew "supabase/tap/supabase"

# Data
brew "duckdb"
brew "greenmask"
brew "parallel"
brew "parquet-cli"
brew "postgresql@14"

# Media
brew "ffmpeg"
brew "tmux"
brew "watchman"

# Casks
cask "alacritty"
cask "graphql-playground"
cask "wave"

# VS Code extensions
vscode "amazonwebservices.amazon-q-vscode"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "amazonwebservices.codewhisperer-for-command-line-companion"
vscode "eamodio.gitlens"
vscode "hashicorp.terraform"
vscode "hediet.vscode-drawio"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-vscode-remote.remote-containers"
vscode "vscodevim.vim"
